{% set name = "hicsv-python" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hicsv-python-{{ version }}.tar.gz
  sha256: da63fcfc10e5255d2cb6860fe3f71dc68eb39c70a1135ae97b0a05efdd5a79af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - numpy >=1.23
    - python >=3.10

test:
  imports:
    - hicsv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/shntrnkgw/hicsv
  summary: Python implementation of the Header-Included Comma-Separated Values (hicsv) file format.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - shntrnkgw
